config/routes.rb
Rails.application.routes.draw do


  get '/recipes/types_index' => 'recipes#types_index'
  get '/recipes/types_index/:type' => 'recipes#by_type'
  get '/recipes/favoriterecipe' => 'recipes#favoriterecipe'
  get '/recipes/famousrecipe' => 'recipes#famousrecipe'
  get '/myprofile' => 'pages#myprofile'
  get '/contactus' => 'pages#contactus'
  root :to =>'pages#home'
  resources :users, :only => [:new, :create]
  get '/login' =>'session#new'  #sign in frm
  post '/login' => 'session#create' #sign in action
  delete '/login' =>'session#destroy' #sign out
  resources :foodtypes #plural
  resources :recipes #plural

  # put '/recipes/:id/recipe' => 'recipes#favourite' as favourite_recipe
  # resources :recipes do
  #  put :favourite, :on => :member

   resources :recipes do
    member do
      put "favorite" => "recipes#favorite"
      put "unfavorite" => "recipes#unfavorite"
    end
      put :favorite, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates :recipe_id, :uniqueness => { :scope => :user_id }
end

app/models/foodtype.rb
# == Schema Information
#
# Table name: foodtypes
#
#  id         :integer          not null, primary key
#  title      :text
#  recipe_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Foodtype < ApplicationRecord
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :text
#  food_desc    :text
#  Image        :text
#  prep_time    :text
#  cook_time    :text
#  no_of_serves :text
#  spice_level  :text
#  recipe_type  :text
#  foodtype_id  :integer
#  ingredients  :text
#  procedure    :text
#  country      :text
#  city         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ApplicationRecord
  has_and_belongs_to_many :foodtypes , :optional => true
  has_many :favorite_recipes
  def self.search(search)
    where("name ILIKE ? OR ingredients ILIKE ? OR procedure ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#

class User < ApplicationRecord
  has_secure_password
  has_many :recipes
  validates :email, :presence => true, :uniqueness => true
  has_many :favorite_recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :fetch_user
  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present? #this prevents horrors if you reseed
  end
end

app/controllers/foodtypes_controller.rb
class FoodtypesController < ApplicationController
  def index
      @foodtypes = Foodtype.all
    end

    def new
      @foodtype = Foodtype.new
    end
    def create
      foodtype = Foodtype.create foodtype_params
      redirect_to foodtype

    end
    def edit
      @foodtype = Foodtype.find params[:id]
    end
    def update
      foodtype = Foodtype.find params[:id]
      foodtype.update foodtype_params
      redirect_to foodtype
    end
    def show
      @foodtype = Foodtype.find params[:id]
    end
    def destroy
      foodtype = Foodtype.find params[:id]
      foodtype.destroy
      redirect_to foodtypes_path
    end
    #strong params - whitelist
    private
    def foodtype_params
      params.require(:foodtype).permit(:title, :recipe_id,:shortname)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController


  def index

    if params[:search]
      @recipes = Recipe.search(params[:search]).order(:created_at)
    else
      @recipes = Recipe.all.order(:created_at)
    end

    # @recipes = Recipe.all.order(:created_at)
  end

  def famousrecipe
    # @recipes = Recipe.all.order(:nofviews)
    # @recipes = Recipe.all.where("nofviews is not null").order("nofviews desc")
    @recipes = Recipe.all.where("nofviews is not null").order("nofviews desc").limit(3)
    render :index
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.create recipe_params
    recipe.user_id = @current_user.id

    recipe.foodtype_ids = params[:recipe][:foodtype_ids]
    recipe.save
    cloudinary = Cloudinary::Uploader.upload(params[:recipe][:image],:public_id => recipe.id)
    recipe.update :image => cloudinary["url"]
    redirect_to recipe
  end

  def edit
    @recipe = Recipe.find params[:id]
  end

  def update
    recipe = Recipe.find params[:id]
    recipe.update recipe_params
    recipe.user_id = @current_user.id
    # raise:hell
    recipe.foodtypes.destroy
    recipe.foodtype_ids = params[:recipe][:foodtype_ids]
    recipe.save

    if params[:recipe][:image].present?
      cloudinary = Cloudinary::Uploader.upload(params[:recipe][:image],:public_id => recipe.id)
      recipe.update :image => cloudinary["url"]
    end



    redirect_to recipe

  end

  def show
    @recipe = Recipe.find params[:id]
    if @recipe.nofviews.nil?
      @recipe.update :nofviews => 1
    else
      @recipe.update :nofviews => 1 + @recipe.nofviews
    end

    @favorited = FavoriteRecipe.find_by(user: @current_user, recipe: @recipe).present?
  end

  def destroy
    recipe = Recipe.find params[:id]
    recipe.destroy
    redirect_to recipes_path
  end

  def types_index
    @foodtypes = Foodtype.all
  end

  def by_type
    foodtype = Foodtype.find_by :shortname => params[:type]
    @recipes = foodtype.recipes
    render :index
  end

  def favoriterecipe
    @recipes =  @current_user.favorite_recipes.map(&:recipe) # Study this
    render :index
  end

  def favorite
    @recipe = Recipe.find(params[:id])
    type = params[:type]
    if type == "favorite"
      @current_user.favorite_recipes.create :recipe => @recipe
      redirect_to @recipe
    elsif type == "unfavorite"
      @current_user.favorite_recipes.find_by(:recipe => @recipe).destroy
        redirect_to @recipe
    end
  end




  private
  def recipe_params
    params.require(:recipe).permit(:name, :food_desc, :image, :prep_time,:cook_time, :no_of_serves, :spice_level, :recipe_type, :foodtype_id, :ingredients, :procedure, :country, :city )
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    end
    def create
      # find the user based on their email
      @user  = User.find_by :email => params[:email]
      #if teh password autheticates
      if @user.present? && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash[:error] = "Invalid username or password"
        redirect_to login_path
      end

        #remeber this in teh session in the Session
      # else
        #send them to the login page again
    end
    def destroy
      session[:user_id] = nil
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new

    end

    def create
      # User.create user_params
      @user = User.new user_params
      if @user.save

        redirect_to root_path# if it worked !
      else
        render :new # show new page again
      end
    end
    private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodtypes_helper.rb
module FoodtypesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foodtypes/_form.html.erb
<!-- FORM HELPER form_for -->
<%= form_for @foodtype do |f| %>
<div class = "formlog">

  <%= f.label :shortname %>
  <%= f.text_field :shortname, :autofocus => true , autofocus:true %>

  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true %>
  <label></label>
  <%= f.submit :class => 'btnlogin' %>
</div>

<% end %>

app/views/foodtypes/edit.html.erb
<h1>Edit Foodtype</h1>

<%= render :partial => 'form' %>

app/views/foodtypes/index.html.erb
<h1>Food Types</h1>

<% @foodtypes.each do |foodtype| %>
<ul>
  <!-- <li><%= link_to foodtype.shortname,  "/recipes/types_index/#{foodtype.shortname}" %> - <%= foodtype.title  %></li> -->
  <li>
    <%= link_to foodtype.shortname,foodtype %> - <%= foodtype.title  %>
  </li>

</ul>


<% end %>

app/views/foodtypes/new.html.erb
<h1>New Food Types</h1>

<%= render :partial => 'form' %>

app/views/foodtypes/show.html.erb
<h1>Foodtypes</h1>
<ul>
  <li><%= @foodtype.shortname %></li>
  <li><%= @foodtype.title %></li>
</ul>
<% if @current_user.present?  %>
  <div class = "controls">
    <%= link_to 'Edit Food Type', edit_foodtype_path(@foodtype) %>
    <%= link_to 'Delete Food Type', @foodtype, :method =>'delete', :data => {:confirm => 'Are you sure?'} %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class = "container">
      <header>
        <div class ="headtag">

          <% if @current_user.present? %>
            <%= link_to "Sign Out #{ @current_user.email}", login_path, :method =>'delete'%>
          <% else  %>
            <%= link_to 'Sign Up', new_user_path %>
            <%= link_to 'Sign In', login_path %>
          <% end %>
          <%=  link_to cl_image_tag("homepage_icon") %>
        </div>



        <!-- <div class = "logo">

        </div> -->
        <!-- <%=  image_tag ("https://cdn.dribbble.com/users/80372/screenshots/371321/anton.png")%> -->

      </header>
      <div class="nav">
        <nav>

          <%= link_to 'HOME', root_path ,class:'navmenu'%>
          <%= link_to 'RECIPES', recipes_path,class:'navmenu' %>
          <%= link_to 'SPECIALITY MENU', recipes_types_index_path,class:'navmenu' %>
          <%= link_to 'TOP RECIPES', recipes_famousrecipe_path,class:'navmenu' %>
          <%= link_to 'CONTACT US', contactus_path ,class:'navmenu'%>

        </nav>

      </div>

      <div class = "Searchform">
        <%= form_tag(recipes_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Recipes", class:'searchtext' %>
          <%= submit_tag "🔍 Search", :name => nil , :class => 'searchbtn' %>

        <% end %>
      </div>
      <%= yield %>

      <footer>
        <div class = "footnav">
          <%= link_to 'Home', root_path ,class:'navmenu1'%>
          <!-- <%= link_to 'Contact us', contactus_path ,class:'navmenu1'%> -->
          <!-- <%= link_to 'Recipes', recipes_path,class:'navmenu1' %> -->
          <% if @current_user.present? %>
            <%= link_to 'New Recipe', new_recipe_path ,class:'navmenu1'%>
            <%= link_to 'All Food Types', foodtypes_path,class:'navmenu1' %>
            <!-- <%= link_to 'New Foodtype', new_foodtype_path ,class:'navmenu1'%>
            <%= link_to 'All Food Types', foodtypes_path,class:'navmenu1' %> -->
          <% end %>
        </div>
        <div class = "footnav1">
          <%= link_to 'Recipes', recipes_path,class:'navmenu1' %>
          <% if @current_user.present? %>
            <!-- <%= link_to 'New Recipe', new_recipe_path ,class:'navmenu1'%> -->
            <%= link_to 'My Favourites', recipes_favoriterecipe_path ,class:'navmenu1'%>
            <%= link_to 'New Foodtype', new_foodtype_path ,class:'navmenu1'%>
            <!-- <%= link_to 'All Food Types', foodtypes_path,class:'navmenu1' %> -->
          <% end %>
        </div>
        <div class = "footnav2">
          <%= link_to 'Contact us', contactus_path ,class:'navmenu1'%>
          <% if @current_user.present? %>
          <%= link_to 'My Profile', myprofile_path ,class:'navmenu1'%>
          <!-- <%= link_to 'My Favourites', recipes_favoriterecipe_path ,class:'navmenu1'%> -->
          <% end %>
        </div>
      </footer>

    </div>
  </body>
</html>

app/views/pages/contactus.html.erb
<div class="container">
  <div class="contactus">
    <%=  cl_image_tag("banner2", :class => "bannerimg1" )%>
    <h1>Contact Us</h1>
    <p>For marketing and content related issues, please contact :
    <a href="mailto:abc@abc.co">Marketing Dept.</a></p>

    <p>For technical support and other site related enquiries, please contact :
    <a href="mailto:abc@abc.co">Technical Dept.</a></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">

  <!-- <% if @current_user.present? %>
    Welcome back <%= @current_user.email %>
  <% end %> -->

    <%=  cl_image_tag("banner1", :class => "bannerimg" )%>



  <p>We are living in an environment where being unhealthy has become normal. Over half of adults and more than one in five children in NSW are overweight or obese, increasing their risk of heart disease, cancer, stroke and type 2 diabetes later in life.</p>
  <div class="homepagec">
    <%=  cl_image_tag("banner2", :class => "bannerimg1" )%>
    <p>
      The good news? This website is the ideal place where you can find healthy recipes that will help in making changes to your lifestyle. You can also find vegetarian, vegan, gluten-free as well as lactose-free recipes. On becoming a member, you can not only view recipes but also add your own creations for the world to discover. Feel free to share these recipes with friends and family.
    </p>



  </div>


  <p>
    It's never too late to make a change for yourself or your family. Small changes to your lifestyle can make a big difference. We need to change normal. We need to make healthy normal.
  </p>



</div>

app/views/pages/myprofile.html.erb
<h1>My Profile</h1>

app/views/recipes/_form.html.erb
<div class ="alignn">

  <%= form_for(@recipe, :html => { :multipart => true }) do |f| %>
  <%= f.label :'Recipe Name' %>
  <%= f.text_field :name,pattern:"^[^,]*[^ ,][^,]*$",:maxlength=>"22", :placeholder => 'Acai Bowl Recipe', class: "foodname", autofocus:true %>
  <%= f.label :"Recipe Description"  %>
  <%= f.text_area :food_desc ,class: "fooddesc", :placeholder => 'Acai is one of the best known sources of antioxidants. Antioxidants are plant-based chemicals which are great for overall health and fighting free radicals within the body.' %>
  <div class = "alignn2">
    <%= f.label :prep_time %>
    <%= f.text_field :prep_time, class:"preptime", :placeholder => '10 mins' %>
    <%= f.label :cook_time %>
    <%= f.text_field :cook_time, class:"cooktime" , :placeholder => '20 mins' %>
    <%= f.label :no_of_serves %>
    <!-- <%= f.text_field :no_of_serves , class: "noofserves" , :placeholder => '2 Serves' %> -->
    <%= f.text_field :no_of_serves , pattern:"[1-9]", class: "noofserves" , :placeholder => '2' %>

  </div>
  <div class="foodty">

    <!-- <%= f.label :recipe_type %>
    <%= f.text_field :recipe_type %> -->

    <%= f.label :recipe_type %>
    <%= f.select :recipe_type, ['Starter', 'Mains', 'Dessert', 'Drinks'], :include_blank => true %>

    <!-- <%= f.label :foodtype_id %>
    <%= f.select :foodtype_id, Foodtype.pluck(:title, :id), :include_blank => true %> -->

    <div class="field">
      <%= f.label "Food Type:" %><br />
      <%= f.collection_check_boxes :foodtype_ids, Foodtype.all, :id, :title do |b| %>
        <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
    </div>


  </div>

  <%= f.label :ingredients %>
  <%= f.text_area :ingredients,class: "ingredients" , :placeholder => '4 tbs acai powder,1 cup frozen raspberries' %>
  <%= f.label :procedure %>
  <%= f.text_area :procedure ,class: "procedure" , :placeholder => 'Blend the acai powder, frozen berries, milk, spinach leaves and honey together' %>

  <%= f.label :image %><br>
  <% if @recipe.image.present? %>
    <%=  cl_image_tag(@recipe.id, :class => 'thumb', :transformation=>[
      {:height => 700, :crop=>"scale"},
      {:overlay=>"black_bar",:gravity=>"north", :opacity=>60 , :flags=>"relative", :width=>1, :height=>0.2,:crop=>"scale"},
      {:overlay => "text:Quicksand_30px_bold:#{@recipe.name}",:color=>"white",:gravity => :north_west, :x => 20, :y => 20,:width =>500, :crop => "fit", :flags=>"relative"}
      ])  %>
  <% end %>

  <%= f.file_field :image %>

  <!-- <%= f.label :image %>
  <%= f.url_field :image, :required => true %> -->

  <div class = "origin">
    <%= f.label :country %>
    <%= f.text_field :country %>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
    <label></label>

    <%= f.submit 'Create Recipe', :class => 'btnsubmit' %>
  <% end %>

</div>

app/views/recipes/bytype.html.erb
<% @foodtypes.each do |foodtype| %>

  <li><%= link_to foodtype.shortname,  "/recipes/types_index/#{foodtype.shortname}" %> - <%= foodtype.title  %></li>

<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<div class = "alignc">
  <%= render :partial=> 'form' %>
</div>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>
<div class = "alignc">

  <% @recipes.each do |recipe| %>
    <% if recipe.image.present? %>

    <!-- <div class = "thumb">
      <%= link_to cl_image_tag(recipe.id),recipe %>

    </div> -->
    <!-- {:overlay=>"black_bar", :gravity=>"north", :width=>1.0, :height=>0.12, :flags=>"relative", :opacity=>60}, -->

    <!-- <% recipename = recipe.name.delete(' ') %> -->
    <%=  link_to cl_image_tag(recipe.id, :class => "thumb", :transformation=>[
      {:height => 350, :crop=>"scale" },
      {:overlay=>"black_bar",:gravity=>"north", :opacity=>60 , :flags=>"relative", :width=>1, :height=>0.2,:crop=>"scale"},
      {:overlay => "text:Quicksand_30_bold:#{recipe.name}",:color=>"white",:gravity => :north_west, :x => 20, :y => 20,:width =>500, :crop => "fit", :flags=>"relative"}

      ]) ,recipe  %>

    <% end %>


  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipes</h1>
<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<h1></h1>

<div class = "alignc">

  <% if @recipe.image.present? %>
    <%=  link_to cl_image_tag(@recipe.id, :class => "feature", :transformation=>[
      {:height => 700, :crop=>"scale"},
      {:overlay=>"black_bar",:gravity=>"north", :opacity=>60 , :flags=>"relative", :width=>1, :height=>0.2,:crop=>"scale"},
      {:overlay => "text:Quicksand_30px_bold:#{@recipe.name}",:color=>"white",:gravity => :north_west, :x => 20, :y => 20,:width =>500, :crop => "fit", :flags=>"relative"}
      ]) ,@recipe.image  %>


  <% end %>


    <div class = "fooddisp">
      <% if @recipe.foodtypes.present? %>
        <% @recipe.foodtypes.each do |foodtype| %>
              <!-- <p><%= foodtype.shortname %></p> -->
              <div class="tooltip"><%= foodtype.shortname %>
                <span class="tooltiptext"><%= foodtype.title %></span>
              </div>
        <% end %>
      <% end %>


      <div class = "fav">
        <!-- <button type="button"><i class="fa fa-heart"></i><span class="badge">favorite</span></button> -->

          <% if @current_user %>
            <% if @favorited %>
            <%= button_to "Unfavourite ☹", favorite_recipe_path(@recipe , type: "unfavorite"), method: :put,   :class=> "favbutton" %>

              <!-- <%= button_to "unfavorite", favorite_recipe_path(@recipe , type: "unfavorite"), method: :put %> -->
            <% else %>
            <%= button_to "Add to favourite ♥", favorite_recipe_path(@recipe, type: "favorite"), method: :put  , :class=> "unfavbutton"%>
              <!-- <%= button_to "favorite", favorite_recipe_path(@recipe, type: "favorite"), method: :put %> -->
            <% end %>
          <% end %>
        </div>
          <div class = "socialmedia">
            <%= social_share_button_tag(@recipe.name) %>
            <!-- <%= social_share_button_tag(@recipe.name, :allow_sites => %w(twitter facebook)) %> -->

          </div>

      </div>



      <!-- </div>

      <% if @current_user %>


        <%= link_to "favorite", favorite_recipe_path(@recipe, type: "favorite"), method: :put %>
        <%= link_to "unfavorite", favorite_recipe_path(@recipe, type: "unfavorite"), method: :put %>
      <% end %>
    </div> -->






      <main>
          <p><%= @recipe.food_desc %></p>
          <p>Origin: <%= @recipe.city %>, <%= @recipe.country %></p>
      </main>

      <aside>
        <div class = "asideTop">
          <p><%= fa_icon "apple", text: "Recipe Type: " %><%= @recipe.recipe_type %></p>
          <p><%= fa_icon "hourglass", text:"Prep time: " %><%= @recipe.prep_time %></p>
        </div>

        <div class = "asideBottom">
          <p><%= fa_icon "hourglass-end", text:"Cook time: "%><%= @recipe.cook_time %></p>
          <p><%= fa_icon "spoon", text:"No of serves: "%><%= @recipe.no_of_serves %></p>
        </div>

      </aside>
    </div>

    <p><strong>Ingredients:</strong></p>
    <% ingredients = @recipe.ingredients.split(",") %>

    <% ingredients.each do |ingredient| %>
      <p><%= fa_icon "caret-right"%> <%=    ingredient %></p>
    <% end %>

    <p><strong>Procedure:</strong></p>

    <% procedures = @recipe.procedure.split(".") %>
      <ol>
        <% procedures.each do |procedure| %>
        <li><%= procedure %>.</li>
        <% end %>
      </ol>
  <% if @current_user.present? && @current_user.id == @recipe.user_id %>
    <div class = "controls">
      <%= link_to 'Edit Recipe', edit_recipe_path(@recipe)  %>
      <%= link_to 'Delete Recipe', @recipe, :method => 'delete', :data =>{:confirm =>'Are you sure ?'}%>

    </div>
  <% end %>

app/views/recipes/types_index.html.erb
<h1>Recipe Types</h1>
<% @foodtypes.each do |foodtype| %>
<ul>
  <li><%= link_to foodtype.shortname,  "/recipes/types_index/#{foodtype.shortname}" %> - <%= foodtype.title  %></li>
  <!-- <li><%= link_to foodtype.title, foodtype %></li> -->
  <!-- <%= link_to foodtype.shortname, "/recipes/types_index/#{ foodtype.shortname }" %> -->

</ul>
<% end %>

app/views/session/new.html.erb
<div class ="formfood">
  <h1>Log in</h1>
  <h2><%= flash[:error] %></h2>
  <%= form_tag login_path do  %>
    <div class = "formlog">
        <%= label_tag  :email %>
        <%= email_field_tag :email %>

        <%= label_tag  :password %>
        <%= password_field_tag :password %>
        <label></label>


        <%= submit_tag "Log in", :class => "btnlogin" %>
    </div>
</div>







<% end %>

app/views/users/new.html.erb
<div class ="formfood">
  <h1>Sign Up</h1>
  <h2></h2>
  <% if @user.errors.any?  %>
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg.capitalize %></li>
      <% end %>
    </ol>
    <!-- <h1>You Screwed something, you dumb terminal</h1> -->
  <% end %>

  <%= form_for @user do |f| %>
    <div class = "formlog">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus:true %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
        <label></label>

        <%= f.submit "Sign up!" , :class => "btnlogin" %>
      </div>
  <% end %>
</div>